import { StyleSheet, Dimensions } from "react-native";

export const styles = StyleSheet.create({
  bgImage: {
    justifyContent: "flex-end",
    width: Dimensions.get("window").width,
    height: Dimensions.get("window").height,
  },
  formContainer: {
    position: "relative",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: "#ffffff",
    minHeight: "67.5%",
    paddingTop: 92,
    paddingBottom: 78,
    paddingHorizontal: 16,
    borderTopRightRadius: 25,
    borderTopLeftRadius: 25,
  },
  userIcon: {
    position: "absolute",
    top: 0,
    marginHorizontal: (Dimensions.get("window").width - 120) / 2,
    transform: [{ translateY: -60 }],
    width: 120,
    height: 120,
    backgroundColor: "#F6F6F6",
    borderRadius: 16,
  },
  addIcon: {
    position: "absolute",
    right: -12.5,
    bottom: 14,
  },
  formTitle: {
    fontFamily: "Roboto-Medium",
    fontWeight: "500",
    fontSize: 30,
    lineHeight: 35,
    letterspacing: 0.01,
    color: "#212121",
  },
  form: {
    display: "flex",
    width: "100%",
    marginTop: 33,
  },
  input: {
    fontFamily: "Roboto-Regular",
    fontSize: 16,
    lineHeight: 19,
    height: 50,
    paddingHorizontal: 16,
    marginBottom: 16,
    color: "#212121",
    borderWidth: 1,
    borderRadius: 8,
  },
  showPass: {
    position: "absolute",
    right: 16,
    top: 16,
    fontFamily: "Roboto-Regular",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 19,
    color: "#1B4371",
  },
  button: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: 50,
    backgroundColor: "#FF6C00",
    borderRadius: 100,
  },
  buttonText: {
    fontFamily: "Roboto-Regular",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 19,
    color: "#ffffff",
  },
  entryText: {
    fontFamily: "Roboto-Regular",
    fontWeight: "400",
    fontSize: 16,
    lineHeight: 19,
    marginTop: 16,
    color: "#1B4371",
  },
});
