import { StyleSheet, Dimensions } from "react-native";

export const styles = StyleSheet.create({
  bgImage: {
    position: "relative",
    flex: 1,
    width: "100%",
    minHeight: "100%",
  },
  container: {
    position: "absolute",
    top: 0,
    width: "100%",
    minHeight: Dimensions.get("screen").height,
    paddingTop: 147,
  },
  postsContainer: {
    flex: 1,
    width: "100%",
    paddingHorizontal: 16,
    paddingTop: 92,
    paddingBottom: 100,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    backgroundColor: "#ffffff",
  },
  avatarBox: {
    position: "absolute",
    top: -60,
    left: (Dimensions.get("window").width - 120) / 2,
    width: 120,
    height: 120,
    backgroundColor: "#F6F6F6",
    borderRadius: 16,
  },
  changeAvatarButton: {
    position: "absolute",
    bottom: 9,
    right: -12.5,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    width: 25,
    height: 25,
    borderRadius: 50,
    backgroundColor: "#ffffff",
    borderWidth: 1,
    borderColor: "#E8E8E8",
  },
  logoutBtn: {
    position: "absolute",
    top: 24,
    right: 16,
  },
  uesrName: {
    fontFamily: "Roboto-Medium",
    fontSize: 30,
    lineHeight: 35,
    letterSpacing: 0.01,
    textAlign: "center",
    color: "#212121",
    marginBottom: 33,
  },
});
